// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: delivery_agent.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddDeliveryAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *AddDeliveryAgentRequest) Reset() {
	*x = AddDeliveryAgentRequest{}
	mi := &file_delivery_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeliveryAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeliveryAgentRequest) ProtoMessage() {}

func (x *AddDeliveryAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeliveryAgentRequest.ProtoReflect.Descriptor instead.
func (*AddDeliveryAgentRequest) Descriptor() ([]byte, []int) {
	return file_delivery_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AddDeliveryAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddDeliveryAgentRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type AddDeliveryAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddDeliveryAgentResponse) Reset() {
	*x = AddDeliveryAgentResponse{}
	mi := &file_delivery_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDeliveryAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDeliveryAgentResponse) ProtoMessage() {}

func (x *AddDeliveryAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDeliveryAgentResponse.ProtoReflect.Descriptor instead.
func (*AddDeliveryAgentResponse) Descriptor() ([]byte, []int) {
	return file_delivery_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AddDeliveryAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignAgentToOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId uint32 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OrderId uint32 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *AssignAgentToOrderRequest) Reset() {
	*x = AssignAgentToOrderRequest{}
	mi := &file_delivery_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentToOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentToOrderRequest) ProtoMessage() {}

func (x *AssignAgentToOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentToOrderRequest.ProtoReflect.Descriptor instead.
func (*AssignAgentToOrderRequest) Descriptor() ([]byte, []int) {
	return file_delivery_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AssignAgentToOrderRequest) GetAgentId() uint32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

func (x *AssignAgentToOrderRequest) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type AssignAgentToOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AssignAgentToOrderResponse) Reset() {
	*x = AssignAgentToOrderResponse{}
	mi := &file_delivery_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignAgentToOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignAgentToOrderResponse) ProtoMessage() {}

func (x *AssignAgentToOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignAgentToOrderResponse.ProtoReflect.Descriptor instead.
func (*AssignAgentToOrderResponse) Descriptor() ([]byte, []int) {
	return file_delivery_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AssignAgentToOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_delivery_agent_proto protoreflect.FileDescriptor

var file_delivery_agent_proto_rawDesc = []byte{
	0x0a, 0x14, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a,
	0x17, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x34, 0x0a, 0x18, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x19, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x1a, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0xc6, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x41, 0x64,
	0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x59, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_agent_proto_rawDescOnce sync.Once
	file_delivery_agent_proto_rawDescData = file_delivery_agent_proto_rawDesc
)

func file_delivery_agent_proto_rawDescGZIP() []byte {
	file_delivery_agent_proto_rawDescOnce.Do(func() {
		file_delivery_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_agent_proto_rawDescData)
	})
	return file_delivery_agent_proto_rawDescData
}

var file_delivery_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_delivery_agent_proto_goTypes = []any{
	(*AddDeliveryAgentRequest)(nil),    // 0: proto.AddDeliveryAgentRequest
	(*AddDeliveryAgentResponse)(nil),   // 1: proto.AddDeliveryAgentResponse
	(*AssignAgentToOrderRequest)(nil),  // 2: proto.AssignAgentToOrderRequest
	(*AssignAgentToOrderResponse)(nil), // 3: proto.AssignAgentToOrderResponse
}
var file_delivery_agent_proto_depIdxs = []int32{
	0, // 0: proto.DeliveryAgentService.AddDeliveryAgent:input_type -> proto.AddDeliveryAgentRequest
	2, // 1: proto.DeliveryAgentService.AssignAgentToOrder:input_type -> proto.AssignAgentToOrderRequest
	1, // 2: proto.DeliveryAgentService.AddDeliveryAgent:output_type -> proto.AddDeliveryAgentResponse
	3, // 3: proto.DeliveryAgentService.AssignAgentToOrder:output_type -> proto.AssignAgentToOrderResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_delivery_agent_proto_init() }
func file_delivery_agent_proto_init() {
	if File_delivery_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_agent_proto_goTypes,
		DependencyIndexes: file_delivery_agent_proto_depIdxs,
		MessageInfos:      file_delivery_agent_proto_msgTypes,
	}.Build()
	File_delivery_agent_proto = out.File
	file_delivery_agent_proto_rawDesc = nil
	file_delivery_agent_proto_goTypes = nil
	file_delivery_agent_proto_depIdxs = nil
}
